version: "3.9"

services:
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  temporal:
    ports:
      - "7233:7233"

  temporal-ui:
    ports:
      - "8233:8080"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres_data: