services:
  postgres:
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  temporal:
    ports:
      - "27233:7233"

  temporal-ui:
    ports:
      - "28233:8080"

  minio:
    ports:
      - "29000:9000"
      - "29001:9001"

volumes:
  postgres_data:
